//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Detail
    {
        public int DetailID { get; set; }
        [Display(Name = "Answer ID")]
        public int AnswerID { get; set; }
        [Display(Name = "Topic ID")]
        public int TopicID { get; set; }
        [Display(Name = "Answer by students")]
        public string DetailAnswer { get; set; }

        public virtual Answer Answer { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
