//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Answer = new HashSet<Answer>();
        }

        public int StuID { get; set; }
        [Display(Name = "姓名")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string StuName { get; set; }
        [Display(Name = "登录名")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string StuLoginName { get; set; }
        [Display(Name = "密码")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string StuLoginPwd { get; set; }
        [Display(Name = "性别")]
        [Required(ErrorMessage = "{0}是必填项")]
        public bool StuSex { get; set; }
        [Display(Name = "电话")]
        public string StuPhone { get; set; }
        [Display(Name = "Email")]
        public string StuEmail { get; set; }
        [Display(Name = "班级")]
        public string StuGrade { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
    }
}
