//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.Detail = new HashSet<Detail>();
        }

        public int TopicID { get; set; }
        [Display(Name = "Question description")]
        [Required(ErrorMessage = "{0} is required")]
        public string TopicExplain { get; set; }
        [Display(Name = "Score for this question")]
        [Required(ErrorMessage = "{0} is required")]
        public int TopicScore { get; set; }
        [Display(Name = "Type")]
        [Required(ErrorMessage = "{0} is required")]
        public int TopicType { get; set; }
        [Display(Name = "Option A")]
        public string TopicA { get; set; }
        [Display(Name = "Option B")]
        public string TopicB { get; set; }
        [Display(Name = "Option C")]
        public string TopicC { get; set; }
        [Display(Name = "Option D")]
        public string TopicD { get; set; }
        [Display(Name = "Sorting")]
        [Required(ErrorMessage = "{0} is required")]
        public int TopicSort { get; set; }
        [Display(Name = "Correct answer")]
        [Required(ErrorMessage = "{0} is required")]
        public string TopicAnswer { get; set; }
        public int PaperID { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Detail { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
